
package wsdlAuction;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Auction", targetNamespace = "http://webService.auction/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Auction {


    /**
     * 
     * @param arg0
     * @return
     *     returns wsdlAuction.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://webService.auction/", className = "wsdlAuction.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.RegisterUserResponse")
    @Action(input = "http://webService.auction/Auction/registerUserRequest", output = "http://webService.auction/Auction/registerUserResponse")
    public User registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdlAuction.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://webService.auction/", className = "wsdlAuction.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.GetUserResponse")
    @Action(input = "http://webService.auction/Auction/getUserRequest", output = "http://webService.auction/Auction/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "cleanUp", targetNamespace = "http://webService.auction/", className = "wsdlAuction.CleanUp")
    @ResponseWrapper(localName = "cleanUpResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.CleanUpResponse")
    @Action(input = "http://webService.auction/Auction/cleanUpRequest", output = "http://webService.auction/Auction/cleanUpResponse")
    public void cleanUp();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns wsdlAuction.Bid
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://webService.auction/", className = "wsdlAuction.NewBid")
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.NewBidResponse")
    @Action(input = "http://webService.auction/Auction/newBidRequest", output = "http://webService.auction/Auction/newBidResponse")
    public Bid newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Money arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsdlAuction.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://webService.auction/", className = "wsdlAuction.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.GetItemResponse")
    @Action(input = "http://webService.auction/Auction/getItemRequest", output = "http://webService.auction/Auction/getItemResponse")
    public Item getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns wsdlAuction.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "offerItem", targetNamespace = "http://webService.auction/", className = "wsdlAuction.OfferItem")
    @ResponseWrapper(localName = "offerItemResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.OfferItemResponse")
    @Action(input = "http://webService.auction/Auction/offerItemRequest", output = "http://webService.auction/Auction/offerItemResponse")
    public Item offerItem(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Category arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeItem", targetNamespace = "http://webService.auction/", className = "wsdlAuction.RevokeItem")
    @ResponseWrapper(localName = "revokeItemResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.RevokeItemResponse")
    @Action(input = "http://webService.auction/Auction/revokeItemRequest", output = "http://webService.auction/Auction/revokeItemResponse")
    public boolean revokeItem(
        @WebParam(name = "arg0", targetNamespace = "")
        Item arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<wsdlAuction.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findItemByDescription", targetNamespace = "http://webService.auction/", className = "wsdlAuction.FindItemByDescription")
    @ResponseWrapper(localName = "findItemByDescriptionResponse", targetNamespace = "http://webService.auction/", className = "wsdlAuction.FindItemByDescriptionResponse")
    @Action(input = "http://webService.auction/Auction/findItemByDescriptionRequest", output = "http://webService.auction/Auction/findItemByDescriptionResponse")
    public List<Item> findItemByDescription(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
